function ranNum() {
    var x = Math.floor((Math.random() * 28) + 1);
    if (x == 1) document.getElementById("randomPlace").innerHTML = ("BLOC 23");
    else if (x == 1) document.getElementById("randomPlace").innerHTML = ("BLOC 23");
    else if (x == 2) document.getElementById("randomPlace").innerHTML = ("DAM");
    else if (x == 3) document.getElementById("randomPlace").innerHTML = ("MILITARY BASE");
    else if (x == 4) document.getElementById("randomPlace").innerHTML = ("QUARRY");
    else if (x == 5) document.getElementById("randomPlace").innerHTML = ("LOZOFF PASS");
    else if (x == 6) document.getElementById("randomPlace").innerHTML = ("RIVERSIDE");
    else if (x == 7) document.getElementById("randomPlace").innerHTML = ("AIRPORT");
    else if (x == 8) document.getElementById("randomPlace").innerHTML = ("TV STATION");
    else if (x == 9) document.getElementById("randomPlace").innerHTML = ("BLOC 18");
    else if (x == 10) document.getElementById("randomPlace").innerHTML = ("STORAGE TOWN");
    else if (x == 11) document.getElementById("randomPlace").innerHTML = ("SUPERSTORE");
    else if (x == 12) document.getElementById("randomPlace").innerHTML = ("JUNKYARD");
    else if (x == 13) document.getElementById("randomPlace").innerHTML = ("GRAVEYARD");
    else if (x == 14) document.getElementById("randomPlace").innerHTML = ("TORSK BLOC");
    else if (x == 15) document.getElementById("randomPlace").innerHTML = ("VERDANSK STADIUM");
    else if (x == 16) document.getElementById("randomPlace").innerHTML = ("LUMBERYARD");
    else if (x == 17) document.getElementById("randomPlace").innerHTML = ("BONEYARD");
    else if (x == 18) document.getElementById("randomPlace").innerHTML = ("TRAIN STATION");
    else if (x == 19) document.getElementById("randomPlace").innerHTML = ("HOSPITAL");
    else if (x == 20) document.getElementById("randomPlace").innerHTML = ("DOWNTOWN");
    else if (x == 21) document.getElementById("randomPlace").innerHTML = ("FARMLAND");
    else if (x == 22) document.getElementById("randomPlace").innerHTML = ("PROMENADE WEST");
    else if (x == 23) document.getElementById("randomPlace").innerHTML = ("PROMENADE EAST");
    else if (x == 24) document.getElementById("randomPlace").innerHTML = ("KART RACING TRACK");
    else if (x == 25) document.getElementById("randomPlace").innerHTML = ("HILLS");
    else if (x == 26) document.getElementById("randomPlace").innerHTML = ("PARK");
    else if (x == 27) document.getElementById("randomPlace").innerHTML = ("PORT");
    else if (x == 28) document.getElementById("randomPlace").innerHTML = ("PRISON");
}