function ranNum() {
    var x = Math.floor((Math.random() * 28) + 1);
    if (x == 1) window.alert("[" + x + "]" + " BLOC 23");
    else if (x == 1) window.alert("[" + x + "]" + " BLOC 23");
    else if (x == 2) window.alert("[" + x + "]" + " DAM");
    else if (x == 3) window.alert("[" + x + "]" + " MILITARY BASE");
    else if (x == 4) window.alert("[" + x + "]" + " QUARRY");
    else if (x == 5) window.alert("[" + x + "]" + " LOZOFF PASS");
    else if (x == 6) window.alert("[" + x + "]" + " RIVERSIDE");
    else if (x == 7) window.alert("[" + x + "]" + " AIRPORT");
    else if (x == 8) window.alert("[" + x + "]" + " TV STATION");
    else if (x == 9) window.alert("[" + x + "]" + " BLOC 18");
    else if (x == 10) window.alert("[" + x + "]" + " STORAGE TOWN");
    else if (x == 11) window.alert("[" + x + "]" + " SUPERSTORE");
    else if (x == 12) window.alert("[" + x + "]" + " JUNKYARD");
    else if (x == 13) window.alert("[" + x + "]" + " GRAVEYARD");
    else if (x == 14) window.alert("[" + x + "]" + " TORSK BLOC");
    else if (x == 15) window.alert("[" + x + "]" + " VERDANSK STADIUM");
    else if (x == 16) window.alert("[" + x + "]" + " LUMBERYARD");
    else if (x == 17) window.alert("[" + x + "]" + " BONEYARD");
    else if (x == 18) window.alert("[" + x + "]" + " TRAIN STATION");
    else if (x == 19) window.alert("[" + x + "]" + " HOSPITAL");
    else if (x == 20) window.alert("[" + x + "]" + " DOWNTOWN");
    else if (x == 21) window.alert("[" + x + "]" + " FARMLAND");
    else if (x == 22) window.alert("[" + x + "]" + " PROMENADE WEST");
    else if (x == 23) window.alert("[" + x + "]" + " PROMENADE EAST");
    else if (x == 24) window.alert("[" + x + "]" + " KART RACING TRACK");
    else if (x == 25) window.alert("[" + x + "]" + " HILLS");
    else if (x == 26) window.alert("[" + x + "]" + " PARK");
    else if (x == 27) window.alert("[" + x + "]" + " PORT");
    else if (x == 28) window.alert("[" + x + "]" + " PRISON");
}